export const homes = [{
    "id": 0,
    "osoite": "Servin Maijan tie 1",
    "m2": 53, 
    "velaton_hinta": 352, 
    "hoitovastike": 169, 
    "aiempi_keittio_remontti": 2015,
    "aiempi_kylpyhuone_remontti": 2015, 
    "aiempi_pinta_remontti": 2015, 
    "aiempi_putki_remontti": 2015,
    "keittio_remontti_hinta": 15, 
    "kylpyhuone_remontti_hinta": 10, 
    "pinta_remontti_hinta": 15,
    "putki_remontti_hinta": 20, 
    "keittion_kayttoika": 10, 
    "kylpyhuoneen_kayttoika": 10, 
    "pinta_kayttoika": 10,
    "putki_kayttoika": 10
},
{
    "id": 1,
    "osoite": "Servinkuja 5",
    "m2": 55, 
    "velaton_hinta": 360, 
    "hoitovastike": 178, 
    "aiempi_keittio_remontti": 2015,
    "aiempi_kylpyhuone_remontti": 2015, 
    "aiempi_pinta_remontti": 2015, 
    "aiempi_putki_remontti": 2015,
    "keittio_remontti_hinta": 15, 
    "kylpyhuone_remontti_hinta": 10, 
    "pinta_remontti_hinta": 15,
    "putki_remontti_hinta": 20, 
    "keittion_kayttoika": 10, 
    "kylpyhuoneen_kayttoika": 10, 
    "pinta_kayttoika": 10,
    "putki_kayttoika": 10
},
{
    "id": 0,
    "osoite": "Jämeräntaival 1",
    "m2": 20, 
    "velaton_hinta": 222, 
    "hoitovastike": 109, 
    "aiempi_keittio_remontti": 2015,
    "aiempi_kylpyhuone_remontti": 2015, 
    "aiempi_pinta_remontti": 2015, 
    "aiempi_putki_remontti": 2015,
    "keittio_remontti_hinta": 15, 
    "kylpyhuone_remontti_hinta": 10, 
    "pinta_remontti_hinta": 15,
    "putki_remontti_hinta": 20, 
    "keittion_kayttoika": 10, 
    "kylpyhuoneen_kayttoika": 10, 
    "pinta_kayttoika": 10,
    "putki_kayttoika": 10
}]